import React from 'react';
import {
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  CircularProgress,
  Divider,
  Typography,
  Alert,
} from '@mui/material';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import RefreshIcon from '@mui/icons-material/Refresh';
import { useNarrative } from '../../hooks/useApi';
import { useStation } from '../../hooks/useStation';

const PROVIDER_COLORS: Record<string, string> = {
  local: '#80cbc4',
  openai: '#74aa9c',
  anthropic: '#ce93d8',
};

const PROVIDER_LABELS: Record<string, string> = {
  local: 'LM Studio (Local)',
  openai: 'OpenAI',
  anthropic: 'Anthropic',
};

export function NarrativePanel() {
  const { stationId, stationName } = useStation();
  const { data, loading, error, generate } = useNarrative(
    stationId,
    stationName,
  );

  return (
    <Card>
      <CardContent>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
          <AutoAwesomeIcon sx={{ color: 'primary.main', fontSize: 20 }} />
          <Typography variant="h6">AI Narrative Analysis</Typography>
        </Box>
        <Typography
          variant="caption"
          color="text.secondary"
          sx={{ display: 'block', mb: 2 }}
        >
          Plain-English interpretation generated by{' '}
          <strong>mistral-7b-instruct-v0.3</strong> via LM Studio (or your
          configured provider). All numbers come from the deterministic
          analytics engine — the LLM only narrates them.
        </Typography>
        <Divider sx={{ mb: 2 }} />

        {!stationId && (
          <Typography color="text.secondary" variant="body2">
            Select a station to generate a narrative.
          </Typography>
        )}

        {stationId && !data && !loading && !error && (
          <Button
            variant="contained"
            onClick={generate}
            startIcon={<AutoAwesomeIcon />}
          >
            Generate Narrative
          </Button>
        )}

        {loading && (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, py: 2 }}>
            <CircularProgress size={20} />
            <Box>
              <Typography variant="body2" color="text.secondary">
                Analyzing with mistral-7b-instruct-v0.3…
              </Typography>
              <Typography variant="caption" color="text.disabled">
                Local inference takes 5–15s depending on your hardware
              </Typography>
            </Box>
          </Box>
        )}

        {error && (
          <Alert severity="warning" sx={{ mb: 2 }}>
            <Typography variant="body2" fontWeight={600}>
              {error}
            </Typography>
            {(error.includes('unavailable') || error.includes('LM Studio')) && (
              <Typography variant="caption" display="block" mt={0.5}>
                Fix: Open LM Studio → Local Server tab → load
                mistral-7b-instruct-v0.3 → click Start Server
              </Typography>
            )}
            <Button
              size="small"
              variant="outlined"
              onClick={generate}
              sx={{ mt: 1 }}
            >
              Retry
            </Button>
          </Alert>
        )}

        {data && (
          <Box>
            <Box sx={{ display: 'flex', gap: 1, mb: 2, flexWrap: 'wrap' }}>
              <Chip
                label={PROVIDER_LABELS[data.provider] ?? data.provider}
                size="small"
                sx={{
                  bgcolor: `${PROVIDER_COLORS[data.provider] ?? '#90a4ae'}22`,
                  color: PROVIDER_COLORS[data.provider] ?? '#90a4ae',
                  fontWeight: 600,
                  fontSize: 11,
                }}
              />
              <Chip
                label={data.model}
                size="small"
                variant="outlined"
                sx={{ fontSize: 10 }}
              />
              <Chip
                label={`Generated ${new Date(data.generatedAt).toLocaleTimeString()}`}
                size="small"
                variant="outlined"
                sx={{ fontSize: 10, opacity: 0.6 }}
              />
            </Box>

            <Typography
              variant="body2"
              sx={{ lineHeight: 1.85, whiteSpace: 'pre-line', mb: 2 }}
            >
              {data.narrative}
            </Typography>

            <Button
              size="small"
              variant="outlined"
              onClick={generate}
              startIcon={<RefreshIcon />}
            >
              Regenerate
            </Button>
          </Box>
        )}
      </CardContent>
    </Card>
  );
}
