import { WaterBill } from './legislation.types';

export const WATER_BILLS: WaterBill[] = [
  {
    id: 'CA-AB93-2025',
    title: 'California Assembly Bill 93 — Data Center Water Disclosure Act',
    shortTitle: 'CA AB 93',
    scope: 'CA',
    status: 'vetoed',
    sponsor: 'Assembly Member Friedman',
    date: '2025-10-15',
    summary:
      'Would have required data center operators to submit annual water consumption reports to local water suppliers and disclose estimated usage before receiving business licenses or construction permits. Vetoed by Governor Newsom citing regulatory burden concerns.',
    url: 'https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260AB93',
    tags: ['disclosure', 'datacenter', 'water-reporting', 'california'],
    aiRelated: true,
  },
  {
    id: 'US-AIEIA-2024',
    title: 'AI Environmental Impacts Act of 2024',
    shortTitle: 'AI Environmental Impacts Act',
    scope: 'federal',
    status: 'introduced',
    sponsor: 'Sen. Edward Markey (D-MA)',
    date: '2024-09-12',
    summary:
      'Directs NIST to develop standards for assessing the environmental impact of AI systems, including water and energy consumption. Requires federal agencies to assess and disclose AI-related environmental costs. Introduced but not yet advanced from committee.',
    url: 'https://www.congress.gov/bill/118th-congress/senate-bill/5036',
    tags: ['ai', 'federal', 'environmental-impact', 'nist', 'disclosure'],
    aiRelated: true,
  },
  {
    id: 'IL-SB2400-2025',
    title: 'Illinois SB 2400 — Data Center Environmental Reporting',
    shortTitle: 'IL SB 2400',
    scope: 'IL',
    status: 'committee',
    date: '2025-02-01',
    summary:
      'Proposes quarterly reporting requirements for data centers above 100MW capacity on water withdrawal, consumption, and return flows. Would require submission to the Illinois EPA and public disclosure on a state portal.',
    url: 'https://www.ilga.gov/legislation/104/SB/10400SB2400.htm',
    tags: ['disclosure', 'datacenter', 'water-reporting', 'illinois', 'quarterly'],
    aiRelated: true,
  },
  {
    id: 'VA-HB1922-2025',
    title: 'Virginia HB 1922 — Data Center Water Use Transparency Act',
    shortTitle: 'VA HB 1922',
    scope: 'VA',
    status: 'monitoring',
    date: '2025-01-15',
    summary:
      'Introduced to require water use impact assessments for new data center developments exceeding 50MW in Loudoun County (Data Center Alley). Particularly relevant given Northern Virginia handles approximately 70% of global internet traffic.',
    url: 'https://lis.virginia.gov/cgi-bin/legp604.exe?251+sum+HB1922',
    tags: ['virginia', 'loudoun', 'datacenter', 'water-assessment', 'data-center-alley'],
    aiRelated: true,
  },
  {
    id: 'US-CWAA-2024',
    title: 'Clean Water Accessibility Act of 2024',
    shortTitle: 'Clean Water Accessibility Act',
    scope: 'federal',
    status: 'committee',
    sponsor: 'Rep. Raul Ruiz (D-CA)',
    date: '2024-06-20',
    summary:
      'Addresses water access equity and infrastructure funding for underserved communities. Includes provisions for protecting municipal water supplies from industrial drawdown without disclosure. Relevant to communities near major data center corridors.',
    url: 'https://www.congress.gov/bill/118th-congress/house-bill/8912',
    tags: ['federal', 'water-access', 'equity', 'infrastructure', 'municipal'],
    aiRelated: false,
  },
  {
    id: 'NJ-A3415-2025',
    title: 'New Jersey A3415 — Data Center Water Sustainability Standards',
    shortTitle: 'NJ A3415',
    scope: 'NJ',
    status: 'introduced',
    date: '2025-03-01',
    summary:
      'Would require new data centers seeking permits in New Jersey to demonstrate water use efficiency metrics (WUE) below 1.5 L/kWh and to implement water recycling systems where technically feasible.',
    url: 'https://www.njleg.state.nj.us/bill-search/2024/A3415',
    tags: ['new-jersey', 'datacenter', 'water-efficiency', 'WUE', 'permits'],
    aiRelated: true,
  },
  {
    id: 'US-WIIN-REAUTH-2024',
    title: 'Water Infrastructure Improvements for the Nation (WIIN) Reauthorization',
    shortTitle: 'WIIN Reauthorization',
    scope: 'federal',
    status: 'monitoring',
    sponsor: 'Senate Environment & Public Works Committee',
    date: '2024-11-01',
    summary:
      'Reauthorization of key water infrastructure legislation covering drought resilience, groundwater monitoring, and rural water system investments. Does not yet address AI or datacenter water consumption directly.',
    url: 'https://www.congress.gov/bill/118th-congress/senate-bill/WIIN',
    tags: ['federal', 'infrastructure', 'drought', 'groundwater', 'reauthorization'],
    aiRelated: false,
  },
  {
    id: 'EU-AIACT-ENV-2024',
    title: 'EU AI Act — Environmental Impact Provisions',
    shortTitle: 'EU AI Act (Environmental)',
    scope: 'federal',
    status: 'signed',
    date: '2024-08-01',
    summary:
      'The EU AI Act, which entered into force August 2024, includes provisions requiring providers of general-purpose AI models with systemic risk to report energy consumption. Water consumption reporting is not yet mandated but is under active discussion by the EU Commission.',
    url: 'https://artificialintelligenceact.eu/',
    tags: ['eu', 'international', 'ai-act', 'energy', 'systemic-risk', 'reporting'],
    aiRelated: true,
  },
];
